main: hr.helmiaRebuilt.helmiaRebuiltFinal
name: HelmiaRebuilt
version: 0.0.1
author: Minkster09
api-version: 1.21
description: Helmia Rebuilt Plugin
commands:
  helmiarebuilt:
    aliases: [hr, helmia, rebuilt]
    description: "Multi-Purpose Helmia Rebuilt Command"
    usage: "/helmiarebuilt <function> <function-details>"
    permission: op
    permission-message: &cYou do not have permission to run this command!
  gmc:
    aliases: [gamemodecreative, tgmc]
    permission: op
    permission-message: &cYou do not have permission to run this command!
  gmsp:
    aliases: [gamemodespectator, tgmsp]
    permission: op
    permission-message: &cYou do not have permission to run this command!
  gms:
    aliases: [gamemodesurvival, tgms]
    permission: op
    permission-message: &cYou do not have permission to run this command!
  gma:
    aliases: [gamemodeadventure, tgma]
    permission: op
    permission-message: &cYou do not have permission to run this command!


